import{StyleSheet, Dimensions} from 'react-native'



export default function getStyles(isDarkMode){
    const { temaCor } = useTheme();
    const { width, height } = Dimensions.get('window');


    const background = isDarkMode ? '#313131ff' : '#ffffffff'
    const tituloBack = isDarkMode ? "#1E1E1E" : '#ebebebff'
    const font = isDarkMode ? '#ffffffff' : "#000000ff" 

    return StyleSheet.create({
    container:{
        width:'100%',
        height:'100%',
        display:'flex',
        flexDirection:'row',
        backgroundColor:background,
    },
    loadingContainer: {
        width:'100%',
        height:'100%',
        justifyContent: 'center',
        alignItems: 'center',
        backgroundColor: isDarkMode ? '#000' : '#fff',
    },
    loadingText: {
        marginTop: 20,
        fontSize: 16,
        color: isDarkMode ? '#fff' : '#000',
    },
    titulo:{
        width:'100%',
        height:height*0.075,
        display:'flex',
        backgroundColor: background,
        borderBottomColor:Colors[temaCor],
        borderBottomWidth:7,
        
    },
    textTitulo:{
        fontFamily:'inter',
        fontSize:40,
        textAlign:'center',
        
        color: font,
    },
    perfil:{
        width:'100%',
        height:height*0.20,
        borderBottomWidth: 3,
        borderColor:tituloBack,
        display:'flex',
        flexDirection:'row',
        marginTop:height*0.02,
    },
    foto:{
        top:'20%',
        height:width*0.30,
        width:width*0.30,
        display:'flex',
        alignItems:'center',
        justifyContent:'center',
        borderWidth:2,
        borderColor:isDarkMode ? '#ffffffff' : '#313131ff',
        borderRadius:'50%',
        left:'5%',
        backgroundColor:Colors[temaCor],
    },
    fotoImage: {
        height:width*0.30,
        width:width*0.30,
        borderRadius: width*0.15,
    },
    uploadOverlay: {
        position: 'absolute',
        top: 0,
        left: 0,
        right: 0,
        bottom: 0,
        backgroundColor: 'rgba(0,0,0,0.5)',
        borderRadius: 60,
        justifyContent: 'center',
        alignItems: 'center',
    },
    info:{
        height:'100%',
        width:'65%',
        display:'flex',
        flexDirection:'column',
        justifyContent:'center',
        left:'5%',
    },
    infoNome:{
        fontSize:17,
        color:font,
        marginTop:10,
        marginLeft:10,
    },
    infoBtn:{
        marginTop:15,
        left:'20%',
        width:'60%',
        paddingHorizontal:9,
        paddingVertical:9,
        backgroundColor:Colors[temaCor],
        display:'flex',
        flexDirection:'column',
        justifyContent:'center',
        borderRadius:10,
    },
    infoBtnText:{
        fontSize:17,
        fontWeight:'600',
        color:'#fff',
        textAlign:'center',
    },
    botao:{
        width:'100%',
        display:'flex',
        flexDirection:'row',
        paddingVertical:7.5,
        paddingHorizontal:20,
        borderBottomWidth:2,
        borderColor:tituloBack,
    },
    botaoTexto:{
        textAlignVertical:'center',
        marginLeft:10,
        fontSize:20,
        color:font,
    },
    modalTemaContainer:{
        width:'100%',
        height:'100%',
        backgroundColor:background,
        display:'flex',
        flexDirection:'column',
        alignItems:'center',
    },
    modalTemaTitulo:{
        width:'100%',
        height:'7%',
        borderBottomWidth:2,
        borderColor:Colors[temaCor],
        display:'flex',
        flexDirection:'row',
        gap:'23%',
    },
    modalTitulo:{
        marginTop:'1%',
        fontFamily:'inter',
        fontSize:35,
        color: font,
    },
    modalLinha:{
        marginTop:'1%',
        width:'100%',
        height:'25%',
        display:'flex',
        flexDirection:'row',
        alignItems:'center',
        justifyContent:'space-between',
        borderBottomWidth:2,
        borderColor:'#6e6e6e3d',
        paddingBottom:10,
        paddingHorizontal:'5%',
    },
    modalTemaView:{
        width:'30%',
        height:'85%',
        backgroundColor:'#6e6e6e15',
        display:'flex',
        flexDirection:'collunn',
        alignItems:'center',
        borderRadius:15,
        borderWidth:2,
        borderColor:'#6e6e6e3d',

    },
    modalTemaText:{
        textAlign:'center',
        bottom:'-3%',
        fontSize:17,
        color:font,
    },
    modalTema:{
        width:'95%',
        height:'80%',
        borderRadius:15,
        display:'flex',
        flexDirection:'row',
        justifyContent:'center',
        alignItems:'center',
    },
    select:{
        transform:[{scale:1.1}],
        borderColor:Colors[temaCor],
    },
    flat:{
        width:'100%',
        height:'auto',
        display:'flex',
        flexDirection:'column',
    },
    flatContainer:{
        marginTop:5,
        left:'5%',
        width:'90%',
        height:60,
        borderBottomWidth:2,
        borderTopWidth:2,
        display:'flex',
        flexDirection:'row',
        alignItems:'center',
        borderColor:'#6e6e6e3d'
    },
    flatCor: {
        width: 45,
        height: 45,
        marginRight: 10,
        borderRadius: 5,
        left:'3%',
        marginRight:30,
      },
    flatText:{
        color:font,
        fontSize:20,
    },
    textTituloModal:{
        marginTop:10,
        fontFamily:'inter',
        fontSize:24,
        textAlign:'center',
        color: font,
    },
    modalContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
  },
  modalContent: {
    backgroundColor: 'white',
    padding: 30,
    borderRadius: 20,
    flex:0.6,
    alignItems: 'center',
    width: '80%',
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 4,
    elevation: 5,
  },
  iconContainer: {
    marginBottom: 20,
  },
  circle: {
    width: 80,
    height: 80,
    borderRadius: 40,
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 3,
    borderColor: '#45a049',
  },
  checkmark: {
    color: 'white',
    fontSize: 40,
    fontWeight: 'bold',
  },
  checkmark2: {
    color: 'black',
    fontSize: 40,
    fontWeight: 'bold',
  },
  title: {
    fontSize: 24,
    fontWeight: 'bold',
    color: '#333',
    marginBottom: 10,
  },
  message: {
    fontSize: 16,
    color: '#666',
    textAlign: 'center',
    marginBottom: 25,
  },
    button: {
    backgroundColor: '#4CAF50',
    paddingVertical: 12,
    paddingHorizontal: 30,
    borderRadius: 25,
  },
  buttonText: {
    color: 'white',
    fontSize: 16,
    fontWeight: '600',
  },
  input: {
    height: 50,
    width: '80%',
    borderWidth: 1,
    borderColor: '#ddd',
    borderRadius: 10,
    paddingHorizontal: 15,
    fontSize: 18,
    backgroundColor: 'white',
    marginVertical: 10,
    textAlign: 'center',
   
  },
})
}